gitstrap:
    version: v1
    github:
        repo:
            # github repository name
            name: argo-sample
            # github repository description
            description: "For check argo"
            # (optional, default false) true if private
            private: false
    templates_dir: "${GOPATH}/src/github.com/rerost/gitstrap-template-go"

