apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dag
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: kube
              secret:
                secretName: kube
          containers:
            - name: exec-workflow
              image: rerost/argo-sample:latest
              command: ["sh", "-c"]
              args: ["argo submit /app/kubernetes/workflow/dag.yaml"]
              volumeMounts:
                - name: kube
                  mountPath: /root
